---
displayName: Che Demo App UI
description: Stack for developing Node.js Angular Web Application
tags: ["Community", "Node.js", "Angular"]
icon: /images/angular.svg
links:
  v2: https://github.com/etsauer/che-demo-app-ui/tree/main
