---
displayName: Guestbook
description: Example guestbook application with NodeJS and MongoDB
tags: ["Community", "Node.js", "Express", "MongoDB", "RealWorld", "ubi8", "Centos"]
icon: /images/nodejs.svg
links:
  v2: https://github.com/rht-labs-events/summit-lab-2023-guestbook/tree/demo